import { Sparkles } from "lucide-react";

import { ExpandablePreview } from "@/components/ui";
import type { FormAction } from "@/components/forms/types";
import type { AiReviewDetails } from "@/lib/ai-review-details";
import { formatDate } from "@/lib/format";

interface AiReviewPanelProps {
  id: string;
  redirectTo: string;
  action: FormAction;
  status: string;
  qualityScore: number | null;
  summary: string | null;
  details: AiReviewDetails;
  reviewedAt: Date | null;
  error: string | null;
  canRunReview: boolean;
  disabledReason: string | null;
}

export function AiReviewPanel({
  id,
  redirectTo,
  action,
  status,
  qualityScore,
  summary,
  details,
  reviewedAt,
  error,
  canRunReview,
  disabledReason,
}: AiReviewPanelProps) {
  const isActive = status === "queued" || status === "processing";
  const actionLabel = status === "failed" ? "Retry AI Review" : "Run AI Review";
  const isDisabled = isActive || !canRunReview;
  const buttonLabel = isActive
    ? "AI Review Active"
    : canRunReview
      ? actionLabel
      : "AI Review Unavailable";
  const hasDetails =
    details.strengths.length > 0 ||
    details.issues.length > 0 ||
    details.suggestions.length > 0 ||
    details.validationNotes.length > 0;

  return (
    <section id="ai-review" className="ui-card p-5 shadow-card">
      <div className="flex items-start justify-between gap-3">
        <div>
          <h2 className="text-base font-semibold text-ink">AI Review</h2>
          <p className="mt-1 text-xs text-muted">Read-only editorial review generated by the LLM worker.</p>
        </div>
        <AiReviewStatusBadge status={status} />
      </div>

      <dl className="mt-4 grid gap-3 text-sm">
        <ReadonlyMeta label="Quality score" value={qualityScore === null ? "-" : `${qualityScore}/100`} />
        <ReadonlyMeta label="Review status" value={reviewStatusLabel(status)} />
        <ReadonlyMeta label="Last reviewed" value={reviewedAt ? formatDate(reviewedAt) : "Not reviewed"} />
      </dl>

      <div className="mt-4">
        <p className="ui-eyebrow">Summary</p>
        <ExpandablePreview collapsedHeight={120} className="mt-2">
          <p className="break-anywhere text-sm leading-6 text-muted">
            {summary ?? reviewEmptyMessage(status)}
          </p>
        </ExpandablePreview>
      </div>

      {hasDetails ? (
        <div className="mt-5 grid gap-4">
          <ReviewDetailList title="Strengths" items={details.strengths} tone="success" />
          <ReviewDetailList title="Issues" items={details.issues} tone="danger" />
          <ReviewDetailList title="Suggestions" items={details.suggestions} tone="accent" />
          <ReviewDetailList title="Validation notes" items={details.validationNotes} tone="warning" />
        </div>
      ) : status === "completed" ? (
        <p className="mt-5 rounded-lg border border-line bg-white/[0.02] p-3 text-sm leading-6 text-muted">
          No detailed findings were stored for this review.
        </p>
      ) : null}

      {error ? (
        <div className="mt-4 rounded-lg border border-danger-300/30 bg-danger-500/10 p-3">
          <p className="text-xs font-semibold uppercase tracking-wide text-danger-100">
            Review error
          </p>
          <p className="mt-1 text-sm leading-6 text-danger-100">{error}</p>
        </div>
      ) : null}

      <form action={action} className="mt-5">
        <input type="hidden" name="id" value={id} />
        <input type="hidden" name="redirectTo" value={redirectTo} />
        <button type="submit" className="ui-btn-secondary w-full" disabled={isDisabled}>
          <Sparkles className="size-4" aria-hidden />
          {buttonLabel}
        </button>
        {disabledReason && !isActive ? (
          <p className="mt-2 text-xs leading-5 text-muted">{disabledReason}</p>
        ) : null}
      </form>
    </section>
  );
}

export function AiReviewStatusBadge({ status }: { status: string }) {
  const tone =
    status === "completed"
      ? "ui-badge-success"
      : status === "failed"
        ? "ui-badge-danger"
        : status === "queued" || status === "processing"
          ? "ui-badge-warning"
          : "ui-badge-neutral";

  return <span className={`ui-badge capitalize ${tone}`}>{status}</span>;
}

function ReadonlyMeta({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-line bg-white/[0.02] p-3">
      <dt className="text-xs uppercase tracking-wide text-muted">{label}</dt>
      <dd className="mt-1 font-medium text-ink">{value}</dd>
    </div>
  );
}

function ReviewDetailList({
  title,
  items,
  tone,
}: {
  title: string;
  items: string[];
  tone: "success" | "danger" | "accent" | "warning";
}) {
  if (items.length === 0) {
    return null;
  }

  const dotClass =
    tone === "success"
      ? "bg-success-400"
      : tone === "danger"
        ? "bg-danger-300"
        : tone === "warning"
          ? "bg-warning-300"
          : "bg-accent-300";

  return (
    <section className="rounded-lg border border-line bg-white/[0.02] p-3">
      <h3 className="text-xs font-semibold uppercase tracking-wide text-muted">{title}</h3>
      <ul className="mt-3 grid gap-2">
        {items.map((item) => (
          <li key={item} className="flex gap-2 text-sm leading-6 text-muted">
            <span aria-hidden className={`mt-2 size-1.5 shrink-0 rounded-full ${dotClass}`} />
            <span className="min-w-0 break-anywhere">{item}</span>
          </li>
        ))}
      </ul>
    </section>
  );
}

function reviewStatusLabel(status: string): string {
  if (status === "idle") return "Not yet reviewed";
  if (status === "queued") return "Queued";
  if (status === "processing") return "Processing";
  if (status === "completed") return "Completed";
  if (status === "failed") return "Failed";
  return status;
}

function reviewEmptyMessage(status: string): string {
  if (status === "queued") {
    return "Review queued. The worker will run when an online LLM is available.";
  }

  if (status === "processing") {
    return "Review processing. Results will appear here when the LLM task completes.";
  }

  if (status === "failed") {
    return "Review failed. Check the error below, then retry when ready.";
  }

  return "Not yet reviewed. Run AI Review to generate editorial metadata for this record.";
}
